### PR TITLE
First step to separate config and code

### PR DESCRIPTION
**Pull request by scimbe**
Perhaps it might be a good idea to split the code in  sections. 
So it is more easy to adapt to other swarm deployments....

### CODE REVIEW

**Comment by torokati44** [comment]
Just a note: It was hardcoded to be "localhost" because:
 - If deployed on AWS using the the tool included in the tutorial, an SSH tunnel is opened from the local machine to the remote swarm manager, forwarding a couple of necessary ports.
 - If deployed on a swarm locally, which the client computer is a part of, Docker should take care of routing the traffic to the appropriate services through its overlay network.
 - If deployed on a local swarm, but used from a non-swarm-member computer: Well, the computer can be added to the swarm easily (presumably), or an SSH tunnel with port forwarding can also be opened manually.

Despite all of this, you are right, it would be great to make some things - including the target host - configurable. But shouldn't the same hostname be passed to the MongoDB connection as well? So the results can be downloaded? With the current Docker stack, the Redis and the Mongo databases are always on the same machine (the manager).

**Comment by scimbe** [comment]
I agree to your argumentation. Of course it is great for the setup you had in mind. 

It was just an one liner to initiate a discussion about the structure of code base for the future work, to support different env...

At least we should setup the code base as generic as possible.  We can support here if you like.

**Comment by torokati44** [comment]
Again, I agree that making the client more configurable is certainly reasonable, I was just providing some explanation for why I thought before that hard-coding was sufficient.
Also what I'm saying is that we should always use the same hostname (configurable or not...) to connect to the MongoDB and the Redis servers, since they are always on the same machine (currently). Is this not the case in your custom setup?

**Comment by scimbe** [comment]
@same hostname
For my understanding yes, as long we use the dns of the docker env...

**Comment by torokati44** [comment]
Closing as stale.

**Pull request closed without merging**
