### PR TITLE
Change statement about packet arrive proportion

### PR DESCRIPTION
**Pull request by edlongman**
The number of packets that arrive is exponentially decreasing as demonstrated by the graph

### CODE REVIEW

**Comment by torokati44** [comment]
Wouldn't an exponential decrease on a graph with logarithmic Y axis make a straight line? :thinking:

**Comment by edlongman** [comment]
I have plotted several forms of the raw data and It doesn't really fit the
description of any exponential or polynomial.
If exponential, on a log y graph, as it is, it would be a straight line
If polynomial on a log x log y graph it would be a straight line.

It is neither, and hard to categorise it as either polynomial or
exponential as it is more complex than that.

I've included the log log graph

**Comment by torokati44** [comment]
You are right, I also tried to fit some polynomes of various degrees on the curve, and none of them would fit. But it's also not a straight line. So neither "polynomially" nor "exponentially" is precise. Perhaps we shouldn't use either term then?

image

**Comment by torokati44** [comment]
What could have been misleading is that taking the logarithm of the values first, and then trying to fit some polynomes, it is much closer. So it "looks" polynomial, on a log-y graph. Sort of.

image

**Comment by edlongman** [comment]
Yep, I think not using either term is a good solution.

Plotting something of the order An^-2.7 fits the latter part of the plot
but that's the best I could do

**Comment by torokati44** [comment]
Resolved by using "rapidly" instead of either "polynomially" or "exponentially". Thank you!

**Pull request closed without merging**
